volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins-network: {}

services:
  jenkins-docker:
    container_name: docker
    image: docker:dind
    command: --storage-driver=overlay2
    ports:
      - "2376:2376"
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-network

  jenkins-server:
    container_name: jenkins-server
    privileged: true
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${JENKINS_PORT}:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home:rw
      - jenkins-docker-certs:/certs/client:ro
    env_file: .env
    environment:
      - JENKINS_PORT=${JENKINS_PORT}
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - jenkins-network
    depends_on:
      - jenkins-docker
    links:
      - jenkins-docker:docker
